### ISSUE TITLE
Makefile Error

### ISSUE THREAD

**Issue by hulihan-start** [roastduck/FreeTensor#381]
All files in the 3rd-party directory cannot be cloned...
When I completely clone all the requirements from 3rd-party, I got this warning:

CMake Warning at /usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2341 (add_library):
  Cannot generate a safe runtime search path for target freetensor_ffi
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libgomp.so.1] in /usr/lib/gcc/x86_64-linux-gnu/9 may be hidden by files in:
      /data/not_backed_up/lihhu/conda_env/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPython.cmake:355 (__Python_add_library)
  3rd-party/pybind11/tools/pybind11NewTools.cmake:187 (python_add_library)
  CMakeLists.txt:212 (pybind11_add_module)

After that, I try to use make -j, and an error happened:
[ 26%] Linking CXX shared library libantlr4-runtime.so
[ 26%] Linking CXX static library libantlr4-runtime.a
[ 26%] Built target antlr4_static
[ 26%] Built target antlr4_shared
make: *** [Makefile:152: all] Error 2

I'm not sure if this error is related to the warning info but I don't know how to solve it.

**Comment by hulihan-start** [comment]
or should I need to build all the other files in 3rd-party directory?
I have no idea😂

**Comment by hulihan-start** [comment]
I updated the public key and can clone recursively. However, the error still occurred...
I do not use antlr before and don't know how to fix this issue

**Comment by roastduck** [comment]
Sorry for the late reply.

"A library was hidden" warning does not necessarily cause an error. It only means there are two libraries with the same name are linked. As long as the libraries with the same name are truly the same, there will be no problem.

I think `make -j` should have showed some other messages before exiting. Can you rerun `make -j` and post it here? You can also drop `-j` to disable parallel building, so there will be fewer messaged printed to the screen.

> or should I need to build all the other files in 3rd-party directory?

You don't have to build files in `3rd-party` directory manually. Just make sure you clone recursively so those files are there.

**Comment by hulihan-start** [comment]
Thanks for your reply. Below is my log when I just use 'make' to make the project. 

Scanning dependencies of target antlr4_shared
[  0%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ANTLRErrorListener.cpp.o
[  0%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ANTLRErrorStrategy.cpp.o
[  0%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ANTLRFileStream.cpp.o
[  0%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ANTLRInputStream.cpp.o
[  0%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/BailErrorStrategy.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/BaseErrorListener.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/BufferedTokenStream.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/CharStream.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/CommonToken.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/CommonTokenFactory.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/CommonTokenStream.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ConsoleErrorListener.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/DefaultErrorStrategy.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/DiagnosticErrorListener.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/Exceptions.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/FailedPredicateException.cpp.o
[  1%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/InputMismatchException.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/IntStream.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/InterpreterRuleContext.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/Lexer.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/LexerInterpreter.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/LexerNoViableAltException.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ListTokenSource.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/NoViableAltException.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/Parser.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ParserInterpreter.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ParserRuleContext.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ProxyErrorListener.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/RecognitionException.cpp.o
[  2%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/Recognizer.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/RuleContext.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/RuleContextWithAltNum.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/RuntimeMetaData.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/Token.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/TokenSource.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/TokenStream.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/TokenStreamRewriter.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/UnbufferedCharStream.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/UnbufferedTokenStream.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/Vocabulary.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/WritableToken.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATN.cpp.o
[  3%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATNConfig.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATNConfigSet.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATNDeserializationOptions.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATNDeserializer.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATNSimulator.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATNState.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ATNStateType.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ActionTransition.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/AmbiguityInfo.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ArrayPredictionContext.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/AtomTransition.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ContextSensitivityInfo.cpp.o
[  4%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/DecisionEventInfo.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/DecisionInfo.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/DecisionState.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/EpsilonTransition.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ErrorInfo.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LL1Analyzer.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerATNConfig.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerATNSimulator.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerAction.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerActionExecutor.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerChannelAction.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerCustomAction.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerIndexedCustomAction.cpp.o
[  5%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerModeAction.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerMoreAction.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerPopModeAction.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerPushModeAction.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerSkipAction.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LexerTypeAction.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/LookaheadEventInfo.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/NotSetTransition.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/OrderedATNConfigSet.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ParseInfo.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ParserATNSimulator.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/PrecedencePredicateTransition.cpp.o
[  6%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/PredicateEvalInfo.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/PredicateTransition.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/PredictionContext.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/PredictionContextCache.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/PredictionContextMergeCache.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/PredictionMode.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/ProfilingATNSimulator.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/RangeTransition.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/RuleTransition.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/SemanticContext.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/SetTransition.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/SingletonPredictionContext.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/StarLoopbackState.cpp.o
[  7%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/Transition.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/TransitionType.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/atn/WildcardTransition.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/dfa/DFA.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/dfa/DFASerializer.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/dfa/DFAState.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/dfa/LexerDFASerializer.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/internal/Synchronization.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/misc/InterpreterDataReader.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/misc/Interval.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/misc/IntervalSet.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/misc/MurmurHash.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/misc/Predicate.cpp.o
[  8%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/support/Any.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/support/Arrays.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/support/CPPUtils.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/support/StringUtils.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/support/Utf8.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/ErrorNodeImpl.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/IterativeParseTreeWalker.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/ParseTree.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/ParseTreeListener.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/ParseTreeVisitor.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/ParseTreeWalker.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/TerminalNodeImpl.cpp.o
[  9%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/Trees.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/Chunk.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/ParseTreeMatch.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/ParseTreePattern.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/ParseTreePatternMatcher.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/RuleTagToken.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/TagChunk.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/TextChunk.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/pattern/TokenTagToken.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPath.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathElement.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathLexer.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathLexerErrorListener.cpp.o
[ 10%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathRuleAnywhereElement.cpp.o
[ 11%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathRuleElement.cpp.o
[ 11%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathTokenAnywhereElement.cpp.o
[ 11%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathTokenElement.cpp.o
[ 11%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathWildcardAnywhereElement.cpp.o
[ 11%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/tree/xpath/XPathWildcardElement.cpp.o
[ 11%] Linking CXX shared library libantlr4-runtime.so
[ 11%] Built target antlr4_shared
Scanning dependencies of target ISL
[ 11%] Creating directories for 'ISL'
[ 11%] No download step for 'ISL'
[ 11%] No patch step for 'ISL'
[ 11%] No update step for 'ISL'
[ 11%] Performing configure step for 'ISL'

**Comment by roastduck** [comment]
The log appears to be free of errors and the building process continues beyond its end. Is the log complete?

**Comment by hulihan-start** [comment]
Here is the log and error in terminal:
/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/3rd-party/antlr/antlr4/runtime/Cpp/runtime/src/Vocabulary.cpp: In static member function ‘static void antlr4::dfa::Vocabulary::__static_initialization_and_destruction_0(int, int)’:
/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/3rd-party/antlr/antlr4/runtime/Cpp/runtime/src/Vocabulary.cpp:12:18: warning: ‘antlr4::dfa::Vocabulary::EMPTY_VOCABULARY’ is deprecated: Use the default constructor of Vocabulary instead. [-Wdeprecated-declarations]
   12 | const Vocabulary Vocabulary::EMPTY_VOCABULARY;
      |                  ^~~~~~~~~~
/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/3rd-party/antlr/antlr4/runtime/Cpp/runtime/src/Vocabulary.cpp:12:18: note: declared here
/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/3rd-party/antlr/antlr4/runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp: In member function ‘void XPathLexer::IDAction(antlr4::RuleContext*, size_t)’:
/data/not_backed_up/lihhu/FreeTensor_experiments/FreeTensor/3rd-party/antlr/antlr4/runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp:166:48: warning: unused parameter ‘context’ [-Wunused-parameter]
  166 | void XPathLexer::IDAction(antlr4::RuleContext *context, size_t actionIndex) {
      |                           ~~~~~~~~~~~~~~~~~~~~~^~~~~~~
./autogen.sh: 2: autoreconf: not found
make[2]: *** [CMakeFiles/ISL.dir/build.make:107: ISL-prefix/src/ISL-stamp/ISL-configure] Error 127
make[1]: *** [CMakeFiles/Makefile2:1667: CMakeFiles/ISL.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by hulihan-start** [comment]
I think it may be because I haven't installed autoreconf...
But I'm sure the previous problem wasn't this.😂 I'll fix it and then update. TY!

**Comment by roastduck** [comment]
Feel free to reopen this issue if there are more problems.
