### ISSUE TITLE
 Build & Run Issue

### ISSUE THREAD

**Issue by anchitDave** [roastduck/FreeTensor#407]
Hello Team,

I am facing some trouble while building freeTensor. Here are the logs for reference,

[ 26%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/tree/xpath/XPathWildcardElement.cpp.o
[ 27%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/tree/xpath/XPathRuleElement.cpp.o
[ 27%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/tree/xpath/XPathWildcardAnywhereElement.cpp.o
[ 27%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/tree/xpath/XPathLexer.cpp.o
[ 27%] Building CXX object 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/tree/xpath/XPathTokenElement.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/build.make:90: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/ANTLRErrorStrategy.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/build.make:160: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/BufferedTokenStream.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [3rd-party/z3/src/util/CMakeFiles/util.dir/build.make:188: 3rd-party/z3/src/util/CMakeFiles/util.dir/fixed_bit_vector.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/build.make:370: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/LexerNoViableAltException.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/build.make:230: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/ConsoleErrorListener.cpp.o] Error 1
compilation terminated.
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/build.make:300: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/InputMismatchException.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/build.make:258: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/DiagnosticErrorListener.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/build.make:216: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/CommonTokenStream.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/build.make:188: 3rd-party/antlr/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_shared.dir/src/CommonToken.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.

It looks like the termination is because of out of memory I suppose. But It would be great if you could provide some insights.

Current Memory situation [WSL2]: 
12GB + 4GB Swap

Thank you in advance!

**Comment by roastduck** [comment]
You can try `make` instead of `make -j`, then the files would be compiled in serial, which saves the memory.

**Comment by anchitDave** [comment]
My bad. Thank you!
